version: '2'
services:
  nexttrip-app:
    image: nexttrip
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://nexttrip-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=nextTrip
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  nexttrip-mongodb:
    extends:
      file: mongodb.yml
      service: nexttrip-mongodb
